% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\hypertarget{red-knot-dfa-simplified-summary}{%
\subsection{Red Knot DFA Simplified
Summary}\label{red-knot-dfa-simplified-summary}}

This is a brief summary of the DFA conducted on roselaari Red Knots. The
purpose of this work is to determine a formula to be used in the field
to sex birds for satellite attachement purposes.

\hypertarget{sample-size}{%
\subsubsection{Sample Size}\label{sample-size}}

We have 86 molecularly sexed birds from Nome and 103 molecularly sexed
birds from Grays Harbor that have the four core measurements -- diagonal
tarsus, wing, total head, and culmen. We have a male bias sample from
both Nome, AK (81.4\% male) and Grays Harbor, WA (56.3\% male). The
extremely bias ratio in Nome is due to our capture techniques targeting
brood rearing birds in recent years.

\hypertarget{male-female-sexual-size-dimorphism}{%
\subsubsection{Male-Female Sexual Size
Dimorphism}\label{male-female-sexual-size-dimorphism}}

As expected, females were significantly larger in three out of four of
our measurements. Females were significantly larger in total head
(\emph{P}\textless.001), culmen (\emph{P}\textless.001), and wing
(\emph{P}\textless.001), but not significantly larger in diagonal tarsus
(\emph{P}=.12).

\begin{figure}

{\centering \includegraphics{REKN_DFA_simplified_summary_files/figure-latex/unnamed-chunk-3-1} 

}

\caption{Figure 2. Density plots of each sexes measurements. Culmen, total head, and wing are the only measurments that showed significant difference between the two sexes.}\label{fig:unnamed-chunk-3}
\end{figure}

\hypertarget{using-dfa-to-guide-field-sexing}{%
\subsubsection{Using DFA to guide field
sexing}\label{using-dfa-to-guide-field-sexing}}

Using a automated stepwise approach, total head and wing were selected
as the best variables to accurately sex birds.

\begin{verbatim}
## correctness rate: 0.8254;  in: "TotalHead";  variables (1): TotalHead 
## correctness rate: 0.84656;  in: "Wing";  variables (2): TotalHead, Wing 
## 
##  hr.elapsed min.elapsed sec.elapsed 
##        0.00        0.00        3.37
\end{verbatim}

\begin{verbatim}
## method      : lda 
## final model : CHDSex ~ TotalHead + Wing
## <environment: 0x000000001b0f5160>
## 
## correctness rate = 0.8466
\end{verbatim}

A cross-validated review of all biologically relevant variables while
omitting highly correlated variables (total head and culmen, r=0.86) in
the same model, resulted in total head, wing, and tarsus predicting sex
with the highest accuracy. The two-variable model (total head and wing)
selected by the automated approach was a very close second, and is more
meaningful given the lack of separation between males and females in
diagonal tarsus. Moving forward, we will use the total head and wing
model.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(MASS)}

\CommentTok{\#lda using all variables}
\NormalTok{jacknife1 \textless{}{-}}\StringTok{ }\KeywordTok{lda}\NormalTok{(CHDSex}\OperatorTok{\textasciitilde{}}\NormalTok{.,}\DataTypeTok{data =}\NormalTok{ all.rekn.outliers.out, }\DataTypeTok{CV =} \OtherTok{TRUE}\NormalTok{)}
\CommentTok{\#lda using culmen, wing, and tarsus}
\NormalTok{jacknife2 \textless{}{-}}\StringTok{ }\KeywordTok{lda}\NormalTok{(CHDSex}\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{Culmen }\OperatorTok{+}\StringTok{ }\NormalTok{Wing }\OperatorTok{+}\StringTok{ }\NormalTok{TarsusDiagonal, }\DataTypeTok{data =}\NormalTok{ all.rekn.outliers.out, }\DataTypeTok{CV =} \OtherTok{TRUE}\NormalTok{)}
\CommentTok{\#lda using culmen, wing, and total head}
\NormalTok{jacknife3 \textless{}{-}}\StringTok{ }\KeywordTok{lda}\NormalTok{(CHDSex}\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{TotalHead }\OperatorTok{+}\StringTok{ }\NormalTok{Wing }\OperatorTok{+}\StringTok{ }\NormalTok{TarsusDiagonal, }\DataTypeTok{data =}\NormalTok{ all.rekn.outliers.out, }\DataTypeTok{CV =} \OtherTok{TRUE}\NormalTok{)}
\CommentTok{\#lda using total head and wing}
\NormalTok{jacknife4 \textless{}{-}}\StringTok{ }\KeywordTok{lda}\NormalTok{(CHDSex}\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{TotalHead }\OperatorTok{+}\StringTok{ }\NormalTok{Wing, }\DataTypeTok{data =}\NormalTok{ all.rekn.outliers.out, }\DataTypeTok{CV =} \OtherTok{TRUE}\NormalTok{)}
\CommentTok{\#lda using culmen and wing}
\NormalTok{jacknife5 \textless{}{-}}\StringTok{ }\KeywordTok{lda}\NormalTok{(CHDSex}\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{Culmen }\OperatorTok{+}\StringTok{ }\NormalTok{Wing, }\DataTypeTok{data =}\NormalTok{ all.rekn.outliers.out, }\DataTypeTok{CV =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Model output for total head, wing, and tarsus. Note the accuracy is very
similar to total head and wing. Tarsus did not do much to imporve the
model, and any improvements could have been due to random chance.

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Predicted Group
## Actual Group   F   M
##            F  42  19
##            M   9 118
##                                          
##                Accuracy : 0.8511         
##                  95% CI : (0.792, 0.8987)
##     No Information Rate : 0.7287         
##     P-Value [Acc > NIR] : 4.786e-05      
##                                          
##                   Kappa : 0.6451         
##                                          
##  Mcnemar's Test P-Value : 0.08897        
##                                          
##             Sensitivity : 0.8235         
##             Specificity : 0.8613         
##          Pos Pred Value : 0.6885         
##          Neg Pred Value : 0.9291         
##              Prevalence : 0.2713         
##          Detection Rate : 0.2234         
##    Detection Prevalence : 0.3245         
##       Balanced Accuracy : 0.8424         
##                                          
##        'Positive' Class : F              
## 
\end{verbatim}

Model output for total head and wing. Note this model's accuracy is very
similar to total head, wing, and tarus.

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Predicted Group
## Actual Group   F   M
##            F  42  19
##            M  10 117
##                                          
##                Accuracy : 0.8457         
##                  95% CI : (0.786, 0.8942)
##     No Information Rate : 0.7234         
##     P-Value [Acc > NIR] : 5.452e-05      
##                                          
##                   Kappa : 0.6341         
##                                          
##  Mcnemar's Test P-Value : 0.1374         
##                                          
##             Sensitivity : 0.8077         
##             Specificity : 0.8603         
##          Pos Pred Value : 0.6885         
##          Neg Pred Value : 0.9213         
##              Prevalence : 0.2766         
##          Detection Rate : 0.2234         
##    Detection Prevalence : 0.3245         
##       Balanced Accuracy : 0.8340         
##                                          
##        'Positive' Class : F              
## 
\end{verbatim}

The table output shows the total head and wing model correctly
classified 42 females and incorrectly classified 10 females as males,
and correctly classified 117 males and incorrectly classified 19 males
as females. The confusion matrix can be seen below.

\begin{verbatim}
##             Predicted Group
## Actual Group   F   M
##            F  42  19
##            M  10 117
\end{verbatim}

This resulted in accurately classifying 84.57\% of individuals with 95\%
CI (78.6\%, 89.42\%)

\hypertarget{equation-for-field-sexing}{%
\subsubsection{Equation for field
sexing}\label{equation-for-field-sexing}}

Using the total head and wing model, we can extract the coefficients to
create an equation for field sexing an individual.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#run the lda with Total Head, Wing, and Tarsus as variables}
\NormalTok{lda4 \textless{}{-}}\StringTok{ }\KeywordTok{lda}\NormalTok{(CHDSex}\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{TotalHead }\OperatorTok{+}\StringTok{ }\NormalTok{Wing, }\DataTypeTok{data =}\NormalTok{ all.rekn.outliers.out)}

\NormalTok{lda4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## lda(CHDSex ~ TotalHead + Wing, data = all.rekn.outliers.out)
## 
## Prior probabilities of groups:
##         F         M 
## 0.3244681 0.6755319 
## 
## Group means:
##   TotalHead     Wing
## F  67.31803 173.6393
## M  64.72362 169.2449
## 
## Coefficients of linear discriminants:
##                  LD1
## TotalHead -0.4974653
## Wing      -0.1001247
\end{verbatim}

-0.1001247 Wing - 0.4974653 Total Head = LD1

Larger LD1 values indicate the bird is more likely male, while lower LD1
values indicate the bird is more likely female. This model correctly
predicted 86\% of males and 80.8\% of females, for an overall accuracy
of 84.6\%. Is this enough to guide sexing in the field? We can create
new LD1 cutoffs to try and increase this accuracy if necessary. With -1
and 0.59 set as LD1 sexing cutoffs, this sexed 52.3\% of the 189
individuals and 95\% of individuals greater than 0.59 were male, and
95\% of individuals less than -1 were female. These cutoffs should be
adjusted based on project goals and acceptable false-positive risk.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predict4 \textless{}{-}}\StringTok{ }\KeywordTok{predict}\NormalTok{(lda4, }\DataTypeTok{newdata =}\NormalTok{ all.rekn.outliers.out)}

\NormalTok{predict4.df \textless{}{-}}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{type =}\NormalTok{ all.rekn.outliers.out[,}\DecValTok{1}\NormalTok{], }\DataTypeTok{lda =}\NormalTok{ predict4}\OperatorTok{$}\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{REKN_DFA_simplified_summary_files/figure-latex/unnamed-chunk-13-1} \end{center}

\end{document}
